services:
  - type: web
    name: starclub-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma db push --accept-data-loss && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT  
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: starclub-postgres
          property: connectionString

databases:
  - name: starclub-postgres
    databaseName: starclub
    user: starclub
