services:
  - type: web
    name: starclub-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: starclub-postgres
          property: connectionString

databases:
  - name: starclub-postgres
    databaseName: starclub
    user: starclub
